### ISSUE TITLE
clear ng2-datepicker after form submit

### ISSUE THREAD

**Issue by ascuet** [bleenco/ng2-datepicker#244]
I want to clear the date field after form submit. I tried `this.expire_date = null;` where my model is expire_date. But it doesn't work. How can I do it? Obviously I don't want to manually click the clear button in the ui.

**Comment by vaibhavpatil111** [comment]
This will solve your problem.

delete this.expire_date['formatted'];

**Comment by zjx** [comment]
tried delete this.expire_date['formatted'];
and it does not work.

**Comment by nilasissen** [comment]
this works for me!
<ng2-datepicker [options]="options" [inputEvents]="validFormdatepickerInputEvents" formControlName="valid_from" [(ngModel)]="package.valid_from" class="text_area"></ng2-datepicker>

 this.package.valid_from = new DateModel();

**Comment by jkuri** [comment]
if binded to [(ngModel)] you reset it just like any other variable in the form.

**Comment by kuldeeps1ngh** [comment]
You can easily clear selected date using ElementRef:

```
<ng-datepicker [(ngModel)]="empty_date" [options]="options1" #date1></ng-datepicker>  

<button (click)="date1.displayValue=''">Clear Date</button>
```

OR

You can clear it from component also:

```
@ViewChild('date1') date1: ElementRef;

resetDate() {
    this.date1['displayValue']='';
}
```
