### ISSUE TITLE
How to clear the selected date? and How to set a null initial value?

### ISSUE THREAD

**Issue by luckynipun** [bleenco/ng2-datepicker#294]
previously the clear worked for <ng2-datepicker [(ngModel)]="date">.
It is not present in the new <ng-datepicker [(ngModel)]="date">, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/17171812/34977285-f1f61c48-fabf-11e7-9ad7-87ba8159aea2.png)

**Comment by mrSerg** [comment]
Need too this feature. Developers, please help!

**Comment by pkhisticastlight** [comment]
I also need this feature!

**Comment by jkuri** [comment]
I am accepting PRs for that feature. sorry but really busy lately

**Comment by pkhisticastlight** [comment]
https://github.com/bleenco/ng2-datepicker/pull/315

**Comment by jkuri** [comment]
resolved with https://github.com/bleenco/ng2-datepicker/pull/315

**Comment by susheel95** [comment]
Please suggest any other date picker module, if a clear feature is not available in this module
