### ISSUE TITLE
ERROR in NgDatepickerModule is not an NgModule

### ISSUE THREAD

**Issue by Omnisri** [bleenco/ng2-datepicker#295]
Hi, not sure if anyone encountered this. But seeing this issue since yesterday. below is my package.json-

```
"dependencies": {
    "angular2-http-file-upload": "^1.0.6",
    "core-js": "^2.5.1",
    "ng2-accordion": "0.0.15",
    "ng2-datepicker": "^2.1.8",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "1.2.7",
    "@angular/compiler-cli": "4.2.6",
    "@angular/compiler": "4.2.6",
    "@angular/common": "4.2.6",
    "@angular/core": "4.2.6",
    "@angular/forms": "4.2.6",
    "@angular/http": "4.2.6",
    "@angular/router": "^4.0.0",
    "@angular/platform-browser": "4.2.6",
    "@angular/platform-browser-dynamic": "4.2.6",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.90",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "^2.6.1"
```

Should I be updating the version? I also tried re-installing ng2-datepicker.

**Comment by Omnisri** [comment]
Also, the minDate: new Date(Date.now()) seems to now disable selection of today's (current) date. this was not an issue 2 days ago. sorry for raising so many issues, been on a blocker since I get the above issue. I might just be missing some reference or something?

Thank you, for all your hard work on bringing up such good date-picker.

**Comment by praxkan** [comment]
I got the same issue - fix the version to 2.1.8 (remove the ^) - and that works. That was the last working version, guess some recent commit broke something

**Comment by Omnisri** [comment]
@praxkan yes, the I reverted to 2.1.8 and it worked for me too. something in the latest commit must have done the break :) thakyou for response!

**Comment by Omnisri** [comment]
closing, as no longer an issue.
